/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NewsUpdate = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TokenMetric = IDL.Record({
  'status' : IDL.Text,
  'marketCap' : IDL.Opt(IDL.Float64),
  'lastUpdated' : IDL.Int,
  'volume' : IDL.Opt(IDL.Float64),
  'price' : IDL.Opt(IDL.Float64),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addNewsUpdate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllNewsUpdates' : IDL.Func([], [IDL.Vec(NewsUpdate)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLiveWalletBalances' : IDL.Func(
      [IDL.Vec(IDL.Nat8), IDL.Opt(IDL.Vec(IDL.Nat8)), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getNewsUpdate' : IDL.Func([IDL.Nat], [IDL.Opt(NewsUpdate)], ['query']),
  'getNewsUpdatesByContent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(NewsUpdate)],
      ['query'],
    ),
  'getNewsUpdatesByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(NewsUpdate)],
      ['query'],
    ),
  'getNewsUpdatesByTitle' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(NewsUpdate)],
      ['query'],
    ),
  'getNewsUpdatesPaginated' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(NewsUpdate)],
      ['query'],
    ),
  'getSortedNewsUpdates' : IDL.Func([], [IDL.Vec(NewsUpdate)], ['query']),
  'getTokenMetrics' : IDL.Func([], [TokenMetric], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NewsUpdate = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TokenMetric = IDL.Record({
    'status' : IDL.Text,
    'marketCap' : IDL.Opt(IDL.Float64),
    'lastUpdated' : IDL.Int,
    'volume' : IDL.Opt(IDL.Float64),
    'price' : IDL.Opt(IDL.Float64),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addNewsUpdate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllNewsUpdates' : IDL.Func([], [IDL.Vec(NewsUpdate)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLiveWalletBalances' : IDL.Func(
        [IDL.Vec(IDL.Nat8), IDL.Opt(IDL.Vec(IDL.Nat8)), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getNewsUpdate' : IDL.Func([IDL.Nat], [IDL.Opt(NewsUpdate)], ['query']),
    'getNewsUpdatesByContent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(NewsUpdate)],
        ['query'],
      ),
    'getNewsUpdatesByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(NewsUpdate)],
        ['query'],
      ),
    'getNewsUpdatesByTitle' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(NewsUpdate)],
        ['query'],
      ),
    'getNewsUpdatesPaginated' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(NewsUpdate)],
        ['query'],
      ),
    'getSortedNewsUpdates' : IDL.Func([], [IDL.Vec(NewsUpdate)], ['query']),
    'getTokenMetrics' : IDL.Func([], [TokenMetric], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };